export { default as CrossIcon } from './icons/cross-icon.svg'
export { default as PauseIcon } from './icons/pause-icon.svg'
export { default as PlayIcon } from './icons/play-icon.svg'
export { default as ResetIcon } from './icons/reset-icon.svg'
export { default as RightArrowIcon } from './icons/arrow-right.svg'
export { default as TickIcon } from './icons/tick-icon.svg'
